Repository jcpsantos/sparta, pull requests merged in 2022-06, with the labels that each got.

#1 create functions save_df_azure_dw and delete_blob
  extract/__init__.py
  load/__init__.py
  load/load.py
  others/__init__.py
  others/delete.py
  transformation/__init__.py
Labels: enhancement

#2 Developer
  .github/workflows/python-package.yml
  .github/workflows/sphinx_doc.yaml
  .gitignore
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
  load/load.py
  others/__init__.py
  others/delete.py
  requirements.txt
  setup.cfg
  setup.py
  sparta/__init__.py
  sparta/delete.py
  sparta/extract.py
  sparta/load.py
  sparta/secret.py
  sparta/tests/__init__.py
  sparta/tests/test_transformation.py
  sparta/transformation.py
  transformation/__init__.py
Labels: bug, documentation, good first issue

#5 change the name in index doc
  docs/source/index.rst
Labels: documentation
